/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/practice'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/practice' | '/pricing' | '/profile' | '/progress' | '/courses'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/practice'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
